In [ ]:
# 1
import numpy as np
B = int(input("Masukkan Banyaknya Baris Matriks: "))
K = int(input("Masukkan Banyaknya Kolom Matriks: "))
ukuran = K*B
matx = np.random.random(size=(B, K))
print(matx)
while True:
  B2 = int(input("Masukkan Banyaknya Baris untuk Reshape Matriks: "))
  K2 = int(input("Masukkan Banyaknya Kolom untuk Reshape Matriks: "))
  if B2*K2 != ukuran:
    print("Tidak bisa di reshape karena beda ukuran")
    continue 
  else:
    print(matx.reshape(B2, K2))
    break

Masukkan Banyaknya Baris Matriks: 4
Masukkan Banyaknya Kolom Matriks: 2
[[0.61748575 0.22679209]
 [0.15900906 0.76264754]
 [0.33856694 0.82343024]
 [0.63227452 0.12134572]]
Masukkan Banyaknya Baris untuk Reshape Matriks: 2
Masukkan Banyaknya Kolom untuk Reshape Matriks: 4
[[0.61748575 0.22679209 0.15900906 0.76264754]
 [0.33856694 0.82343024 0.63227452 0.12134572]]


In [ ]:
# 2
import numpy as np
B = int(input("Masukkan Banyaknya Baris Matriks: "))
K = int(input("Masukkan Banyaknya Kolom Matriks: "))
while True:
  atas = float(input("Masukkan Batas Atas Matriks: "))
  bawah = float(input("Masukkan Batas Bawah Matriks: "))
  if atas <= bawah :
    print("Batas atas harus lebih banyak dari batas bawah")
    continue
  else:
    break
ukuran = K*B
matx = np.random.uniform(low=bawah, high=atas, size=(B, K))
print(matx)
while True:
  B2 = int(input("Masukkan Banyaknya Baris untuk Reshape Matriks: "))
  K2 = int(input("Masukkan Banyaknya Kolom untuk Reshape Matriks: "))
  if B2*K2 != ukuran:
    print("Tidak bisa di reshape karena beda ukuran")
    continue 
  else:
    print(matx.reshape(B2, K2))
    break

Masukkan Banyaknya Baris Matriks: 4
Masukkan Banyaknya Kolom Matriks: 5
Masukkan Batas Atas Matriks: 5
Masukkan Batas Bawah Matriks: 5
Batas atas harus lebih banyak dari batas bawah
Masukkan Batas Atas Matriks: 5
Masukkan Batas Bawah Matriks: 7
Batas atas harus lebih banyak dari batas bawah
Masukkan Batas Atas Matriks: 7
Masukkan Batas Bawah Matriks: 4
[[4.76727368 6.0876919  5.37588936 5.6055042  6.16431478]
 [6.61934938 6.12916438 4.17804877 5.81116479 4.68466665]
 [5.33972242 5.56872372 5.6419777  4.05067608 5.07602769]
 [6.49660779 4.10374542 6.69542433 5.14818903 5.38874052]]
Masukkan Banyaknya Baris untuk Reshape Matriks: 5
Masukkan Banyaknya Kolom untuk Reshape Matriks: 4
[[4.76727368 6.0876919  5.37588936 5.6055042 ]
 [6.16431478 6.61934938 6.12916438 4.17804877]
 [5.81116479 4.68466665 5.33972242 5.56872372]
 [5.6419777  4.05067608 5.07602769 6.49660779]
 [4.10374542 6.69542433 5.14818903 5.38874052]]


In [ ]:
# 3
import numpy as np
print("1. Buat random Matriks")
print("2. Ubah shape Matriks")
print("3. Ubah ukuran Matriks")
while True:   
  pilih = int(input("pilih 1/2/3: "))
  if pilih == 1 :
    B = int(input("Masukkan Banyaknya Baris Matriks: "))
    K = int(input("Masukkan Banyaknya Kolom Matriks: "))
    while True:
      atas = float(input("Masukkan Batas Atas Matriks: "))
      bawah = float(input("Masukkan Batas Bawah Matriks: "))
      if atas <= bawah :
        print("Batas atas harus lebih banyak dari batas bawah")
        continue
      else:
        break
    ukuran = K*B
    matx = np.random.uniform(low=bawah, high=atas, size=(B, K))
    print(matx)

  elif pilih == 2 :
    B2 = int(input("Masukkan Banyaknya Baris untuk Reshape Matriks: "))
    K2 = int(input("Masukkan Banyaknya Kolom untuk Reshape Matriks: "))
    while True:
      if B2*K2 != ukuran:
        print("Tidak bisa di reshape karena beda ukuran")
        continue 
      else:
        print(matx.reshape(B2, K2))
        break

  elif pilih == 3 :
    B3 = int(input("Masukkan Banyaknya Baris Matriks: "))
    K3 = int(input("Masukkan Banyaknya Kolom Matriks: "))
    # new = np.array(matx)
    new = np.resize(matx,(B3, K3))
    print(new)

  else : 
    break

1. Buat random Matriks
2. Ubah shape Matriks
3. Ubah ukuran Matriks
pilih 1/2/3: 1
Masukkan Banyaknya Baris Matriks: 3
Masukkan Banyaknya Kolom Matriks: 2
Masukkan Batas Atas Matriks: 0
Masukkan Batas Bawah Matriks: 10
Batas atas harus lebih banyak dari batas bawah
Masukkan Batas Atas Matriks: 10
Masukkan Batas Bawah Matriks: 2
[[8.25073371 2.83491923]
 [6.3933133  6.44254626]
 [7.62880493 5.45450559]]
pilih 1/2/3: 3
Masukkan Banyaknya Baris Matriks: 4
Masukkan Banyaknya Kolom Matriks: 2
[[8.25073371 2.83491923]
 [6.3933133  6.44254626]
 [7.62880493 5.45450559]
 [8.25073371 2.83491923]]


KeyboardInterrupt: ignored